version: 2
jobs:
  init_root_gradle_wrapper:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - run:
          name: 'Init root gradlew'
          command: './gradlew --version'
      - save_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle

  init_masterapp_gradle_wrapper:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - restore_cache:
          key: masterapp-gradlew-{{ arch }}
          paths:
            - master/.gradle/
            - ~/.gradle
      - run:
          name: 'Init masterapp gradlew'
          working_directory: master/
          command: './gradlew --version'
      - save_cache:
          key: masterapp-gradlew-{{ arch }}
          paths:
            - master/.gradle/
            - ~/.gradle

  check_requirements_masterapp:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - restore_cache:
          key: masterapp-gradlew-{{ arch }}
          paths:
            - master/.gradle/
            - ~/.gradle
      - run:
          name: 'Check master-app requirements'
          command: './gradlew checkMasterAppRequirements'

  build_masterapp:
    docker:
      - image: circleci/jdk8:0.1.1
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - restore_cache:
          key: masterapp-gradlew-{{ arch }}
          paths:
            - master/.gradle/
            - ~/.gradle
      - run:
          name: 'Clean master-app builds'
          command: './gradlew cleanMasterApp'
      - run:
          name: 'Build master-app'
          command: './gradlew buildMasterApp'
      - save_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - store_artifacts:
          path: master/build/libs/

  check_requirements_micropython_controller:
    docker:
      - image: flintci/pycodestyle
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - run:
          name: 'Check requirements'
          command: './gradlew checkControllerLinterRequirements'

  lint_micropython_controller:
    docker:
      - image: flintci/pycodestyle
    steps:
      - checkout
      - restore_cache:
          key: root-gradlew-{{ arch }}
          paths:
            - .gradle/
            - ~/.gradle
      - run:
          name: 'Lint controller'
          command: './gradlew lintController'

workflows:
  version: 2
  workflow_master_app:
    jobs:
      - init_root_gradle_wrapper
      - init_masterapp_gradle_wrapper:
          requires:
            - init_root_gradle_wrapper
      - check_requirements_masterapp:
          requires:
            - init_masterapp_gradle_wrapper
      - build_masterapp:
          requires:
            - check_requirements_masterapp
  workflow_micropython_controller:
    jobs:
      - init_root_gradle_wrapper
      - check_requirements_micropython_controller:
          requires:
            - init_root_gradle_wrapper
      - lint_micropython_controller:
          requires:
            - check_requirements_micropython_controller
